import type { CmsContent } from "./cms-types";

export const CMS_DEFAULTS: CmsContent = {
  hero: {
    name: "Mohamed Nagy Hassan",
    badge: "Currently Open to Opportunities",
    title1: "Software Testing Engineer",
    title2: "Manual • API • Automation",
    description:
      "Detail-oriented QA Engineer specialized in Manual Testing, API Testing, and Automation with hands-on experience in enterprise assessment systems.",
    location: "Based in Giza, Egypt",
    certification: "ISTQB CTFL Certified",
    experience: "1+ Years",
    profileImage: "",
  },
  about: {
    bio: "I am a Software Testing Engineer with experience in Manual Testing, API Testing, and Automation. I graduated from Ain Shams University and completed the Software Testing Track at ITI. I focus on delivering high-quality software products through structured testing methodologies, API validation, and continuous improvement.",
    profileDetails: [
      { icon: "Briefcase", title: "QC Engineer", sub: "AGI · 2024 — Present" },
      { icon: "GraduationCap", title: "Ain Shams University", sub: "B.Sc. Graduate" },
      { icon: "Award", title: "ISTQB CTFL", sub: "Certified Tester" },
      { icon: "MapPin", title: "Giza, Egypt", sub: "Open to remote / hybrid" },
    ],
    stats: [
      { value: 1, suffix: "+", label: "Years Experience" },
      { value: 500, suffix: "+", label: "Test Cases Executed" },
      { value: 200, suffix: "+", label: "Bugs Reported" },
      { value: 50, suffix: "+", label: "APIs Tested" },
    ],
  },
  experiences: [
    {
      company: "Advanced Group For Information Technology (AGI)",
      position: "Quality Control Engineer",
      duration: "March 2024 — Present",
      current: true,
      items: [
        "Manual Testing for Gourmet assessment platform",
        "API Testing using Postman",
        "Validating integrations and secure data exchange",
        "Collaborating with developers and business teams",
        "Writing bug reports and executing test cases",
        "Regression testing & exploratory testing",
      ],
    },
    {
      company: "ITWORK EDUCATION",
      position: "Software Testing Intern",
      duration: "Dec 2023 — March 2024",
      current: false,
      items: [
        "Manual Testing for Emirates Schools Establishment systems",
        "API Testing for WinjiGo",
        "UI/UX Testing",
        "Testing using Postman and Rest Assured",
        "Bug reporting and issue tracking",
      ],
    },
  ],
  tools: [
    { title: "Testing Skills", icon: "ClipboardCheck", items: ["Manual Testing", "Exploratory Testing", "Regression Testing", "Smoke Testing", "UI/UX Testing", "Mobile Testing", "Security Testing", "Agile Testing", "UAT"] },
    { title: "API Testing", icon: "Network", items: ["Postman", "Rest Assured", "Swagger", "JSON Validation", "XML Validation", "API Testing", "API Automation"] },
    { title: "Automation Testing", icon: "Bot", items: ["Selenium WebDriver", "Java", "TestNG", "Maven", "POM Design Pattern", "Data Driven Testing", "Automation Testing"] },
    { title: "Performance & Security", icon: "ShieldCheck", items: ["JMeter", "Burp Suite", "Performance Testing", "Security Testing Basics"] },
    { title: "Project Management & QA Process", icon: "Kanban", items: ["Jira", "Trello", "Azure DevOps", "SDLC", "STLC", "Bug Reporting", "Test Case Design"] },
    { title: "Technical Skills", icon: "Code2", items: ["SQL", "HTML", "CSS", "JavaScript", "Git", "GitHub", "Database Validation"] },
  ],
  skills: [
    {
      title: "Testing Skills",
      skills: [
        { name: "Manual Testing", level: 95 },
        { name: "API Testing", level: 92 },
        { name: "Automation Testing", level: 80 },
        { name: "Exploratory Testing", level: 88 },
        { name: "Agile Testing", level: 85 },
        { name: "UI/UX Testing", level: 82 },
        { name: "Mobile Testing", level: 75 },
        { name: "Security Testing", level: 70 },
      ],
    },
    {
      title: "Automation & Tools",
      skills: [
        { name: "Selenium WebDriver", level: 82 },
        { name: "Postman", level: 95 },
        { name: "Rest Assured", level: 85 },
        { name: "JMeter", level: 70 },
        { name: "Jira", level: 90 },
        { name: "Trello", level: 85 },
        { name: "Azure DevOps", level: 78 },
        { name: "Burp Suite", level: 65 },
      ],
    },
    {
      title: "Programming & Technical",
      skills: [
        { name: "Java", level: 80 },
        { name: "SQL", level: 85 },
        { name: "HTML", level: 88 },
        { name: "CSS", level: 80 },
        { name: "JavaScript", level: 75 },
        { name: "SDLC", level: 90 },
        { name: "Agile Methodology", level: 90 },
      ],
    },
  ],
  certifications: [
    { name: "ISTQB CTFL", issuer: "Certified Tester Foundation Level", icon: "Award" },
    { name: "Postman Automation Project", issuer: "Hands-on API Automation", icon: "Network" },
    { name: "Rest Assured Course", issuer: "API Test Automation", icon: "Server" },
    { name: "Manual Testing Course", issuer: "QA Foundations", icon: "ClipboardCheck" },
    { name: "API Testing Using Rest Assured", issuer: "Coursera", icon: "GraduationCap" },
  ],
  projects: [
    {
      title: "Trello API Testing Project",
      description: "API testing using Postman with request validation, response validation, assertions, collections, and automated API validation across full Trello REST surface.",
      tech: ["Postman", "API Testing", "JSON", "Newman", "Automation"],
      badge: "API Automation",
      github: "#",
      link: "#",
      image: "",
      showGithubLink: true,
      showLiveUrl: true,
    },
    {
      title: "AI Mortality Prediction — Graduation Project",
      description: "Machine Learning and Deep Learning models including CNN, RNN, and RAIM for ICU mortality prediction with end-to-end data pipeline and model evaluation.",
      tech: ["Python", "AI", "Deep Learning", "CNN", "RNN"],
      badge: "Case Study",
      github: "#",
      link: "#",
      image: "",
      showGithubLink: true,
      showLiveUrl: true,
    },
  ],
  achievements: [
    { value: 500, suffix: "+", label: "Test Cases Executed", icon: "ClipboardCheck" },
    { value: 200, suffix: "+", label: "Bugs Reported", icon: "Bug" },
    { value: 50, suffix: "+", label: "APIs Tested", icon: "Network" },
    { label: "Enterprise Systems Experience", icon: "Building2", text: true },
    { label: "Cross-team Collaboration", icon: "Users", text: true },
  ],
  contact: {
    email: "eng.mohamednagyhassan@gmail.com",
    phone: "+20 106 335 3056",
    location: "6 October, Giza, Egypt",
    linkedin: "https://www.linkedin.com/in/mohamed-nagy-hassan-961956239/",
    github: "https://github.com/MohamedNagyHassan",
  },
  footer: {
    name: "Mohamed Nagy Hassan",
    email: "eng.mohamednagyhassan@gmail.com",
    linkedin: "https://www.linkedin.com/in/mohamed-nagy-hassan-961956239/",
    github: "https://github.com/MohamedNagyHassan",
  },
};
